<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-IQN173AE" failures="3" tests="4" name="TestBanking App" time="18.287" errors="0" timestamp="2020-08-25T15:55:38 ICT">
  <testcase classname="com.inetbanking.testCases.TC_LoginTest_001" name="LoginTest" time="2.479">
    <failure type="java.lang.AssertionError" message="expected [Login | Salesforce3623] but found [Login | Salesforce]">
      <![CDATA[java.lang.AssertionError: expected [Login | Salesforce3623] but found [Login | Salesforce]
at com.inetbanking.testCases.TC_LoginTest_001.LoginTest(TC_LoginTest_001.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase classname="com.inetbanking.testCases.TC_LoginTest_001" name="LoginTest" time="1.315">
    <failure type="java.lang.AssertionError" message="expected [Login | Salesforce3623] but found [Login | Salesforce]">
      <![CDATA[java.lang.AssertionError: expected [Login | Salesforce3623] but found [Login | Salesforce]
at com.inetbanking.testCases.TC_LoginTest_001.LoginTest(TC_LoginTest_001.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase classname="com.inetbanking.testCases.TC_LoginTest_001" name="LoginTest" time="1.114">
    <failure type="java.lang.AssertionError" message="expected [Login | Salesforce3623] but found [Login | Salesforce]">
      <![CDATA[java.lang.AssertionError: expected [Login | Salesforce3623] but found [Login | Salesforce]
at com.inetbanking.testCases.TC_LoginTest_001.LoginTest(TC_LoginTest_001.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase classname="com.inetbanking.testCases.TC_LoginTest_001" name="closing" time="1.267"/>
</testsuite> <!-- TestBanking App -->
